version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  
    commands:
      - npm install --save-dev webpack
      - npm install
    
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  
