version: 0.2

phases:
  install:
  
    commands:
      - apt-get update -y
      - curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash - 
      - apt-get install -y nodejs
      - npm install
    
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  
